package client

import (
	"fmt"
	"os"
	"strings"

	"github.com/Ryliey/ruleconv/internal/compiler"
	"github.com/Ryliey/ruleconv/internal/ir"
	"gopkg.in/yaml.v3"
)

// Mihomo renders rule sets for the mihomo core: YAML rule-providers
// as source, .mrs binaries from `mihomo convert-ruleset`. .mrs supports only the
// domain and ipcidr behaviours, never classical — so Mixed is YAML-only and has
// no binary.
type Mihomo struct{}

func init() { Register(Mihomo{}) }

func (Mihomo) Name() string      { return "mihomo" }
func (Mihomo) SourceExt() string { return ".yaml" }
func (Mihomo) BinaryExt() string { return ".mrs" }

func (Mihomo) SupportsBinary(k Kind) bool { return k == Site || k == IP }

func (Mihomo) RenderSource(rs ir.RuleSet, k Kind) ([]byte, error) {
	var payload []string
	switch k {
	case Site:
		// Keyword/regex cannot be expressed by the domain behaviour; they
		// survive only in the classical Mixed file (sync warns about this).
		for _, d := range rs.Domain {
			payload = append(payload, quoteYAML(d))
		}
		for _, d := range rs.DomainSuffix {
			payload = append(payload, quoteYAML("+."+d))
		}
	case IP:
		for _, c := range rs.IPCIDR {
			payload = append(payload, quoteYAML(c))
		}
	default:
		for _, d := range rs.Domain {
			payload = append(payload, "DOMAIN,"+d)
		}
		for _, d := range rs.DomainSuffix {
			payload = append(payload, "DOMAIN-SUFFIX,"+d)
		}
		for _, d := range rs.DomainKeyword {
			payload = append(payload, "DOMAIN-KEYWORD,"+d)
		}
		for _, d := range rs.DomainRegex {
			payload = append(payload, "DOMAIN-REGEX,"+d)
		}
		for _, c := range rs.IPCIDR {
			payload = append(payload, ipRule(c))
		}
	}
	return renderMihomoYAML(rs.Service, k, payload), nil
}

func (Mihomo) Parse(path string, k Kind) (ir.RuleSet, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return ir.RuleSet{}, err
	}
	var doc struct {
		Payload []string `yaml:"payload"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return ir.RuleSet{}, fmt.Errorf("mihomo parse %s: %w", path, err)
	}
	rs := ir.RuleSet{}
	for _, raw := range doc.Payload {
		entry := strings.TrimSpace(raw)
		if entry == "" {
			continue
		}
		switch k {
		case Site:
			parseDomainEntry(&rs, entry)
		case IP:
			rs.IPCIDR = append(rs.IPCIDR, entry)
		default:
			parseClassicalLine(&rs, entry)
		}
	}
	return rs.Dedup(), nil
}

func (Mihomo) Compile(srcPath string, k Kind, outPath string) error {
	switch k {
	case Site:
		return compiler.MihomoConvert("domain", "yaml", srcPath, outPath)
	case IP:
		return compiler.MihomoConvert("ipcidr", "yaml", srcPath, outPath)
	default:
		return fmt.Errorf("mihomo: mixed/classical rule sets cannot be compiled to .mrs")
	}
}

// BehaviorName returns the mihomo rule-provider behaviour for a kind.
func (Mihomo) BehaviorName(k Kind) string {
	switch k {
	case Site:
		return "domain"
	case IP:
		return "ipcidr"
	default:
		return "classical"
	}
}

// LossyWarning reports keyword/regex matchers the .mrs domain behaviour can't
// represent.
func (Mihomo) LossyWarning(rs ir.RuleSet) string {
	if len(rs.DomainKeyword) > 0 || len(rs.DomainRegex) > 0 {
		return fmt.Sprintf("mihomo domain rule-set (.mrs) cannot represent DOMAIN-KEYWORD/DOMAIN-REGEX; "+
			"%d keyword + %d regex rule(s) are kept only in the mixed classical .yaml",
			len(rs.DomainKeyword), len(rs.DomainRegex))
	}
	return ""
}

func renderMihomoYAML(service string, k Kind, payload []string) []byte {
	var b strings.Builder
	behavior := Mihomo{}.BehaviorName(k)
	fmt.Fprintf(&b, "# %s — mihomo rule-provider (behavior: %s)\n", service, behavior)
	if k == Mixed {
		b.WriteString("# Mixed source — edit here; RuleConv regenerates the split files, binaries and other clients.\n")
	} else {
		b.WriteString("# Generated by RuleConv — do not edit (edit the mixed source instead).\n")
	}
	if len(payload) == 0 {
		b.WriteString("payload: []\n")
		return []byte(b.String())
	}
	b.WriteString("payload:\n")
	for _, p := range payload {
		b.WriteString("  - " + p + "\n")
	}
	return []byte(b.String())
}

func parseDomainEntry(rs *ir.RuleSet, e string) {
	switch {
	case strings.HasPrefix(e, "+."):
		rs.DomainSuffix = append(rs.DomainSuffix, strings.TrimPrefix(e, "+."))
	case strings.HasPrefix(e, "*."):
		rs.DomainSuffix = append(rs.DomainSuffix, strings.TrimPrefix(e, "*."))
	case strings.HasPrefix(e, "."):
		rs.DomainSuffix = append(rs.DomainSuffix, strings.TrimPrefix(e, "."))
	default:
		rs.Domain = append(rs.Domain, e)
	}
}

func parseClassicalLine(rs *ir.RuleSet, line string) {
	parts := strings.Split(line, ",")
	if len(parts) < 2 {
		return
	}
	typ := strings.ToUpper(strings.TrimSpace(parts[0]))
	val := strings.TrimSpace(parts[1])
	switch typ {
	case "DOMAIN":
		rs.Domain = append(rs.Domain, val)
	case "DOMAIN-SUFFIX":
		rs.DomainSuffix = append(rs.DomainSuffix, val)
	case "DOMAIN-KEYWORD":
		rs.DomainKeyword = append(rs.DomainKeyword, val)
	case "DOMAIN-REGEX":
		rs.DomainRegex = append(rs.DomainRegex, val)
	case "IP-CIDR", "IP-CIDR6":
		rs.IPCIDR = append(rs.IPCIDR, val)
	}
}

func ipRule(c string) string {
	if strings.Contains(c, ":") {
		return "IP-CIDR6," + c + ",no-resolve"
	}
	return "IP-CIDR," + c + ",no-resolve"
}

// quoteYAML single-quotes a scalar (doubling embedded quotes) so values like
// "+.example.com" or IPv6 CIDRs parse as plain strings.
func quoteYAML(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
